### PR TITLE
Add license file

### PR DESCRIPTION
**Pull request by blinxen**

### CODE REVIEW

**Comment by blinxen** [comment]
I would appreciate it if this could be merged soon :D.

**Comment by rabbiveesh** [comment]
Would you mind 1) setting the license to the full Artistic License, like tree-sitter-perl and 2) setting up CI to bundle it in the release branch (like you did for ts-perl)?

**Comment by blinxen** [comment]
Thanks for the reply! I commited the requested changes :D.

**Review by rabbiveesh — APPROVED** [review]
thanks!

**Pull request merged**
